### ISSUE TITLE
Error when  building sox

### ISSUE THREAD

**Issue by yuchen-w** [HPCE/hpce-2014-cw2#10]
![issues](https://cloud.githubusercontent.com/assets/3355737/5969275/9670cf0e-a819-11e4-8f4d-cc0114a2d76a.png)
I've just tried to run "make install" after compiling sox, but it returns the errors shown in the screenshot. Has anyone encountered this before?

I'm running Cygwin on Windows.

**Comment by m8pple** [comment]
Is there a space in the filename?

It looks like the working directory is /cygdrive/g/Skydrive/Documents/Work/EE4/3. HPCE/ etc,
with a space between the 3. and the HPCE.

So it is looking for a path called "HPCE/CW2 ..." when at the point it fails.

So I think try removing the space in the directory name?

**Comment by yuchen-w** [comment]
Thank you Dr Thomas!

Didn't realise it was such a simple error.
