### ISSUE TITLE
New deadline dates

### ISSUE THREAD

**Issue by chungcyk** [HPCE/hpce-2014-cw2#11]
Unfortunately I couldn’t make it to the lecture on Tuesday because I had an assessment centre – and hence I’ve left rather confused about the updated deadline system (especially since I can't seem to find the recording on Panopto)

So am I right in saying that, all new deadlines are on Thursdays, and if I choose to use the extended two days, I would hand it in by Saturdays?

I’m just asking since Blackboard system due date says Tuesdays.

Thanks and have a great weekend!

**Comment by m8pple** [comment]
You understanding is correct.

I thought I updated in blackboard too, but I'll check.

**Comment by m8pple** [comment]
You're right - I had updated the visible text in blackboard, but not the actual dates
in the meta-data. I think another situation where instructors tend to use a different
view to students.

Thanks - they are all updated.
