### ISSUE TITLE
Note on ./prepare_submissions.sh

### ISSUE THREAD

**Issue by AugustineTan** [HPCE/hpce-2014-cw2#12]
Just in case people cannot run the script to generate the tar ball. The file is not set to have UNIX line endings. Set to UNIX line endings and it will run.

**Comment by m8pple** [comment]
Hrmm, not sure what is going on there - the intent is that everything should be coming out
in unix line endings, and if I check out in windows (tortoisegit or cygwin command line) or
unix I get a version with unix line endings.

I'll add an note in there in case anyone has the same problem, or someone knows what
I'm doing wrong.

**Comment by bwh10** [comment]
Thanks for the solution! It works like a charm when I set the file to UNIX line endings.

**Comment by m8pple** [comment]
Closing to tidy up.
