### ISSUE TITLE
When extracting the submission tar, files in the subdirectories loses permissions

### ISSUE THREAD

**Issue by AugustineTan** [HPCE/hpce-2014-cw2#13]
When trying to test the submission tar ball I am unable to recreate my environment because the files in /audio cannot be open because they have lost all permissions

```
$ ls -la
total 41
drwxrwxr-x+ 1 Augustine None    0 Jan 31 08:05 .
d---------+ 1 Augustine None    0 Jan 31 08:05 ..
----------  1 Augustine None   61 Jan 31 03:54 .gitignore
----------  1 Augustine None  251 Jan 31 04:16 all_firs_direct.sh
----------  1 Augustine None  481 Jan 31 04:16 all_firs_staged.sh
----------  1 Augustine None   93 Jan 31 04:16 audio_sink.sh
drwxrwxr-x+ 1 Augustine None    0 Jan 31 08:05 coeffs
----------  1 Augustine None  320 Jan 31 04:16 corrupter.sh
----------  1 Augustine None 2629 Jan 31 04:16 fir_filter.c
----------  1 Augustine None  105 Jan 31 04:16 makefile
----------  1 Augustine None 2036 Jan 31 04:16 merge.c
----------  1 Augustine None  185 Jan 31 04:16 mp3_file_src.sh
----------  1 Augustine None   69 Jan 31 04:16 mp3_sink.sh
----------  1 Augustine None   76 Jan 31 04:16 mp3_url_src.sh
----------  1 Augustine None 1737 Jan 31 04:16 passthrough.c
----------  1 Augustine None 1394 Jan 31 04:16 print_audio.c
----------  1 Augustine None 1947 Jan 31 04:16 signal_generator.c
```

Interestingly the files in the base directory i.e makefile maintains its permissions and can be opened. Am I missing another command to restore all the permissions?

**Comment by m8pple** [comment]
It's strange that all permissions are disappearing. The command I use
to extract is just:

```
tar -xzf whatever.tar.gz
```

And I find the permissions of scripts are maintained.

Though looking at the reported permissions for makefile, that has:

```
----------  1 Augustine None  105 Jan 31 04:16 makefile
```

so technically you shouldn't be able to read from that.

Is this happening under mingw or cygwin, as for a native linux it
doesn't seem possible?

**Comment by AugustineTan** [comment]
I am using 64bit cygwin. I believe I was able to do my work because my files had ACLS permissions attached to them. However I believe tar does not preserve these permissions after an extraction. Therefore I explicitly set the permissions to the required files in `prepare_submissions.sh` using chmod 644 giving -rw-rw-r-- and they extracted fine.

**Comment by m8pple** [comment]
Closing this one, as I think it is resolved.
