### ISSUE TITLE
OS X Compatability: time command

### ISSUE THREAD

**Issue by txsl** [HPCE/hpce-2014-cw2#14]
A note for OS X users:

I had a look at Issue #7, and it seems that by default OS X comes installed with a version of time (in /usr/bin/time which doesn't support the `-f` flag, nor the `%e` format.

A call of `which time` in zsh returns

>  time: shell reserved word

and in bash returns /usr/bin/time.

Had a look at installing the proper GNU utilities via Homebrew, but they don't include the `time` function. So OS X users won't get the complete *nix experience unless they use a Virtual Machine, Docker Container or SSH to a _proper_ Linux server. Interested to see if anyone does come up with a fix for this.

And I think @salmanarif is about to note something about compiling C on OS X too.

**Comment by kronocharia** [comment]
If the goal is to just display the time can't we just stick with bash time without needing to adjust the formats?

**Comment by m8pple** [comment]
The bash time command is mostly fine for our purposes, except for the annoying
output format which is difficult to extract and bring into another tool for analysis/graphing.
That was really the only intent of using -f.

The main intent is to show that it is possible and easy to explore large parameter spaces without
pressing return after entering each combination (mainly as I see students doing that, and/or
claiming that two data-points constitutes a linear trend).

Unfortunately the rather parlous state of `time` in the shell has gotten in the way - I'll have to
rethink how to get that message across when I rework for next year.
