### ISSUE TITLE
Merge.c - more details please?

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce-2014-cw2#22]
How are we meant to merge them? Is it meant to be interleaved in blocks of 512? or interleaved sample by sample from each?

Does the OS automatically buffer the streams such that it only goes at the rate the thing downstream consumes, and slows the entire chain down to the slowest part, like with mp3streaming being slowed down to the audio bitrate?

As as sidenote, file IO in C is beyond painful TT_TT, any help would be appreciated

**Comment by kronocharia** [comment]
Hmm so I was meant to average the 2 streams? that makes more sense...

**Comment by m8pple** [comment]
I would apologise for making you do raw file IO, but it's based on experience from a
few years back of people hitting the need to get data in and out of their programs,
and doing it as text using printf and scanf or cin and cout. Their GPU programs were
wonderfully fast, but completely bottlenecked by unnecessary text conversions.
