### ISSUE TITLE
make

### ISSUE THREAD

**Issue by chungcyk** [HPCE/hpce-2014-cw2#5]
Probably a silly question from my part (have never done this before)

I can't seem to "make" the files with it saying that the MakeFile cannot be found, but ls shows they are there... Any ideas?

![image](https://cloud.githubusercontent.com/assets/5358463/5935537/e857c56c-a6d3-11e4-94e3-c107d7aaaf86.png)

**Comment by txsl** [comment]
Is the filename called 'makefile'? And in the root of the repository?

You'd need be in the same directory as where the makefile is located (in this case, the root of the repo) when calling make

On 28 Jan 2015, at 09:58, Michael Chung <notifications@github.com<mailto:notifications@github.com>> wrote:

Probably a silly question from my part (have never done this before)

I can't seem to "make" the files with it saying that the MakeFile cannot be found, but ls shows they are there... Any ideas?

[image]https://cloud.githubusercontent.com/assets/5358463/5935537/e857c56c-a6d3-11e4-94e3-c107d7aaaf86.png

##

**Comment by bwh10** [comment]
The MakeFile should not have any file extensions behind it. It should just be called makefile. 'makefile.txt', 'makefile.unix' etc. should not be valid.

![image](https://cloud.githubusercontent.com/assets/10518447/5935972/061518c6-a6d8-11e4-864e-75f8208d2ca4.png)

**Comment by m8pple** [comment]
@chungcyk Not a silly question, the idea of this exercise is that a lot of the shell stuff is
a bit confusing until you've gone through it a couple of times.

The `makefile` in the lame directory should be created as a side-effect of running `./configure` in the directory. Can you confirm whether the lame configuration completed successfully?

**Comment by chungcyk** [comment]
Thanks for all the response! I've just gone back to do sox again because there was the same problem. There is no makefile in the root and the configure results are as shown below. There was a configure error on C compiler - would that be it?

![image](https://cloud.githubusercontent.com/assets/5358463/5942269/619512ce-a70e-11e4-8b6f-40cb64671e03.png)

**Comment by m8pple** [comment]
Yes, that looks like the problem.

It looks like you don't have any C compilers installed, you can see it trying:
- gcc (the GNU compiler)
- cc (the default unix compiler name, if one exists)
- then cl (the microsoft compiler).

It appears you are using mingw32, I haven't specifically tested that environment (usually
cygwin is slightly easier to use), but I just ran through building lame and sox in mingw32,
and it appears to work fine.

Installation of packages for mingw is handled using mingw-get, there are more
details [here](http://www.mingw.org/wiki/getting_started).

The specific command would be something like `mingw-get`. For example:

![image](https://cloud.githubusercontent.com/assets/3024705/5942964/ece7115c-a712-11e4-848d-f934510c6106.png)

I already had it installed, but you'd see different results.

But as I said, while there is a certain hard-core quality to mingw32, you may find it easier
to switch to cygwin.

**Comment by chungcyk** [comment]
Thanks Dr Thomas! Installed g++ and that seems to have done the job (well it was loading a lot of things on the screen for a few minutes so I assume it's fine for now)

Don't think cygwin are installed on the College PCs on Level 5 - so MinGW will do for now :)
