### ISSUE TITLE
Script typo - Under Part B: Some helper functions

### ISSUE THREAD

**Issue by bwh10** [HPCE/hpce-2014-cw2#6]
Since we are in the <root_repo>/audio folder the script mp3_sink.sh should be written as:
# !/bin/bash

../local/bin/lame -r -s 44.1 --signed --bitwidth 16 - $1

Instead of:
# !/bin/bash

local/bin/lame -r -s 44.1 --signed --bitwidth 16 - $1

After making this change, the following pipe command should then be able to run:

./mp3_url_src.sh http://cas.ee.ic.ac.uk/people/dt10/teaching/2013/hpce/cw2/bn9th_m4.mp3 \
    | ./mp3_sink.sh tmp.mp3

**Comment by m8pple** [comment]
Quite right, I will update.

In an older version I was using something like:

```
#!/bin/bash
$(dirname $0)/../local/bin/lame -r -s 44.1 --signed --bitwidth 16 - $1
```

to make them position independent, but thought it was making it
too complicated, and possibly non portable. Clearly I didn't
edit them out well enough.
