### ISSUE TITLE
200Hz.raw file missing

### ISSUE THREAD

**Issue by bwh10** [HPCE/hpce-2014-cw2#8]
In Part B "dumping signals", the following example command is given:

cat 200hz.raw | head -c 64 | ./print_audio

However, 200hz.raw file was not given in the /audio folder. I think this file should be given as in Part B "Generating Signals", it says: "An example segment is given in 200hz.raw"

**Comment by m8pple** [comment]
You're right - I added the .cvsignore file so that people (well, me) wouldn't accidentally
try to commit large binary files into git, but accidentally excluded the small one that _should_
be there.

**Comment by m8pple** [comment]
BTW, as I'll say in the main file in a minute, it is better to get the file over by "git pull" rather than manually downloading.
