### ISSUE TITLE
FIR filter - Choppy sound 

### ISSUE THREAD

**Issue by bwh10** [HPCE/hpce-2014-cw2#9]
I've implemented the FIR filter and tested it with the following commands:

./merge <(./mp3_file_src.sh bn9th_m4.mp3) <(./signal_generator 800) \
    | ./fir_filter coeffs/f800.csv \
    | ./audio_sink.sh

It works perfectly and I can hear the 800Hz tone get attenuated with no observable effect to the music. 

However, when I cascade 2 notch filters together as shown by the command listed below, I get very 'choppy' and lagged results. It is as if some output samples have been dropped and the remaining output samples have been delayed by a noticeable amount of time. 

./merge <(./mp3_file_src.sh bn9th_m4.mp3) <(./signal_generator 800) \
    | ./fir_filter coeffs/f800.csv \
    | ./fir_filter coeffs/f800.csv \
    | ./audio_sink.sh

Is this effect as expected? Or is there some problem with my code (i.e. not efficient enough)?

**Comment by m8pple** [comment]
That sounds like you are running out of CPU power, which might be the case on some low-powered machines. The FIRs are fairly compute intensive. However, if it worked for one FIR filter, you'd expect the other one to be able to run on the other CPU.

Are the two fir_filter processes stuck at 100% CPU if you look at them in a process/task monitor?

Also, did you add the optimisation flag (-O2) to the makefile?

**Comment by bwh10** [comment]
I just checked my CPU utilization percentages. The first fir_filter is at 13% CPU while the second fir_filter process is at 9% CPU utilization. I think the cause is most likely running out of CPU power. This is because I reran the experiment with 1 FIR filter without the cascade and is giving me the exact same problem although I have not made any code modifications. 

Yes, I've set the compiler optimisation flag set to -O2 without any success. Should I be worried about this? Do I need to write a more highly efficient FIR filter code?

**Comment by m8pple** [comment]
You don't need to particularly worry about it, as I don't really test for performance (unless it
is incredibly slow and times out).

It would be interesting to know why it is so slow though - when you say 13% CPU, is that 13% of
of total CPU time in an 8-core system (i.e. ~12.5%=1/8 th of total CPU power), or 13% of one
CPU in a system with multiple CPUs? The former would be consistent with it saturating one
CPU, the latter wouldn't.

**Comment by m8pple** [comment]
Closing this to tidy up.
